version: '3.9'
services:
  api:
    build:
      context: server
      dockerfile: Dockerfile
    volumes:
      - ./server:/src/server
      - ./server/node_modules:/src/server/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
    environment:
      MONGODB_URL: mongodb://mongo
      REDIS_URL: redis://redis
      NODE_ENV: development
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    container_name: mongo
  redis:
    image: redis:alpine
    container_name: soundCLoud_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
volumes:
  mongo:
  redis-data:
  redis-conf:
