version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - "5000:5000"
      - "9229:9229"
    env_file:
      - ./.env
    depends_on:
      - mongo
      - redis
    environment:
      MONGODB_URL: mongodb://mongo
      REDIS_URL: redis://redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NODE_ENV: development
      PORT: 8080
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    container_name: mongo
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
volumes:
  mongo:
  redis-data:
  redis-conf:
